# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moto', '0001_initial'),
        ('size', '0001_initial'),
        ('ColorProducto', '0001_initial'),
        ('categoria', '0001_initial'),
        ('compra', '0001_initial'),
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precioCosto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de costo')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True)),
                ('DetalleCompraId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.detallecompra', verbose_name='Detalle de compra')),
            ],
            options={
                'verbose_name_plural': 'Registro de productos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
                ('CategoriaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categorias', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código')),
                ('estado', models.BooleanField(default=True)),
                ('ColorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ColorProducto.colorproducto', verbose_name='Color')),
                ('MarcaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marcas', verbose_name='Marca')),
                ('MotoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moto.motos', verbose_name='Moto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.productos', verbose_name='Producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='size.size', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name_plural': 'Detalles del producto',
            },
        ),
    ]
