# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('marca', '0001_initial'),
        ('size', '0001_initial'),
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('CategoriaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categorias', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('Stock', models.IntegerField(verbose_name='Stock')),
                ('MarcaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marcas', verbose_name='Marca')),
                ('MotoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moto.motos', verbose_name='Moto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.productos', verbose_name='Producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='size.size', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name_plural': 'Detalles del producto',
            },
        ),
    ]
