# Generated by Django 4.2 on 2025-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductos',
            name='Stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
    ]
