# Generated by Django 4.2 on 2025-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_detalleproductos_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
