# Generated by Django 4.2 on 2026-04-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_detalleproductos_estado_productos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproductos',
            name='PrecioVenta',
        ),
        migrations.RemoveField(
            model_name='detalleproductos',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='detalleproductos',
            name='precioCompra',
        ),
        migrations.CreateModel(
            name='Registro_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('FechaRegistro', models.DateTimeField(verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True)),
                ('detalleProductoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.detalleproductos', verbose_name='Descripción del producto')),
            ],
            options={
                'verbose_name_plural': 'Registro de productos',
            },
        ),
    ]
