# Generated by Django 4.2 on 2026-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_detalleproductos_precioventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_producto',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
