# Generated by Django 4.2 on 2026-08-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorProducto', '0001_initial'),
        ('producto', '0005_alter_registro_producto_fecharegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductos',
            name='ColorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ColorProducto.colorproducto', verbose_name='Color'),
        ),
    ]
