# Generated by Django 4.2 on 2026-08-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_detallecompra_compraid'),
        ('producto', '0006_detalleproductos_colorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_producto',
            name='detalleProductoId',
        ),
        migrations.AddField(
            model_name='registro_producto',
            name='DetalleCompraId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='compra.detallecompra', verbose_name='Detalle de compra'),
            preserve_default=False,
        ),
    ]
