# Generated by Django 4.2 on 2025-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodoPago', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_compra', models.IntegerField(verbose_name='Número de compra')),
                ('Fecha', models.DateField()),
                ('metodo_Pagoid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodo_pago', verbose_name='Metodo de pago')),
                ('proveedorid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
