# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('NumCompra', models.IntegerField(verbose_name='Número de compra')),
                ('Total', models.IntegerField(verbose_name='Total de la compra')),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='metodo_Pagoid',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedorid',
        ),
    ]
