# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compras_remove_compra_metodo_pagoid_and_more'),
        ('detalleCompra', '0002_rename_cantidad_detallecompra_cantidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
