# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedores_delete_proveedor'),
        ('metodoPago', '0002_metodopago_delete_metodo_pago'),
        ('compra', '0003_delete_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='MetodoPagoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodopago', verbose_name='Metodo de pago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='ProveedoresId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedores', verbose_name='Proveedor'),
        ),
    ]
