# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('Telefono', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('NumCedula', models.CharField(max_length=13, unique=True, verbose_name='Numero de cédula')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
