# Generated by Django 4.2 on 2025-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('num_Cedula', models.CharField(max_length=13, unique=True, verbose_name='Numero de cédula')),
            ],
        ),
    ]
