# Generated by Django 4.2 on 2025-11-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='NumCedula',
            field=models.CharField(max_length=16, unique=True, verbose_name='Numero de cédula'),
        ),
    ]
