# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_rename_num_caja_caja_numcaja_remove_caja_ingreso_and_more'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('Telefono', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('NumCedula', models.CharField(max_length=13, unique=True, verbose_name='Numero de cédula')),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
