# Generated by Django 4.2 on 2025-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleados_numcedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
