# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compras_remove_compra_metodo_pagoid_and_more'),
        ('detalleCompra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='cantidad',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='Precio_costo',
            new_name='PrecioUnitario',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='compraid',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='productoid',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='Subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='CompraId',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra'),
            preserve_default=False,
        ),
    ]
