# Generated by Django 4.2 on 2025-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('moto', '0001_initial'),
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria', verbose_name='Categoria')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marca', verbose_name='Marca')),
                ('motoid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moto.moto', verbose_name='Moto')),
            ],
        ),
    ]
