# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_motos_remove_moto_marcaid'),
        ('categoria', '0002_categorias'),
        ('detalleCompra', '0002_rename_cantidad_detallecompra_cantidad_and_more'),
        ('detalleFactura', '0003_detallefactura_facturaid'),
        ('marca', '0002_marcas_remove_marca_tipoid'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Stock', models.IntegerField(verbose_name='Stock')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('CategoriaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categorias', verbose_name='Categoria')),
                ('MarcaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marcas', verbose_name='Marca')),
                ('MotoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moto.motos', verbose_name='Moto')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
