# Generated by Django 4.2 on 2025-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio costo')),
                ('facturaid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.factura', verbose_name='Factura')),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto', verbose_name='Productos')),
            ],
        ),
    ]
