# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalleFactura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='cantidad',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='total',
            new_name='Subtotal',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='facturaid',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='productoid',
        ),
    ]
