# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalleFactura', '0002_rename_cantidad_detallefactura_cantidad_and_more'),
        ('factura', '0003_facturas_metodopagoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='FacturaId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='Factura'),
            preserve_default=False,
        ),
    ]
