# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalleFactura', '0003_detallefactura_facturaid'),
        ('producto', '0002_productos_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='ProductoId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='producto.productos', verbose_name='Productos'),
            preserve_default=False,
        ),
    ]
