# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
                ('TipoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
