# Generated by Django 4.2 on 2026-04-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoMovimientoCaja', '0001_initial'),
        ('compra', '0004_alter_detallecompra_options_and_more'),
        ('metodoPago', '0002_metodopago_estado'),
        ('origenSaldo', '0001_initial'),
        ('factura', '0008_remove_facturas_metodopagoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True)),
                ('compraCreditoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.comprascredito', verbose_name='Compra al credito')),
                ('compraId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra')),
                ('facturaCreditoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.facturascredito', verbose_name='Factura al credito')),
                ('facturaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='Factura')),
                ('metodoPagoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodopago', verbose_name='Metodo de pago')),
                ('origenSaldoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='origenSaldo.origensaldo', verbose_name='Origen del saldo')),
                ('tipoMovimientoCajaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoMovimientoCaja.tipomovimientocaja', verbose_name='Tipo de movimiento')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de pago',
            },
        ),
    ]
