# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('metodoPago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('estado', models.BooleanField(default=True)),
                ('MovimientoCajaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.movimientocaja', verbose_name='Movimiento de caja')),
                ('metodoPagoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodopago', verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de pago',
            },
        ),
    ]
