# Generated by Django 4.2 on 2026-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoPago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientopago',
            name='MovCaj',
            field=models.BooleanField(default=True),
        ),
    ]
