# Generated by Django 4.2 on 2026-08-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_caja_turnocaja_numcajaid'),
        ('movimientoPago', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientopago',
            name='compraCreditoId',
        ),
        migrations.RemoveField(
            model_name='movimientopago',
            name='compraId',
        ),
        migrations.RemoveField(
            model_name='movimientopago',
            name='facturaCreditoId',
        ),
        migrations.RemoveField(
            model_name='movimientopago',
            name='facturaId',
        ),
        migrations.RemoveField(
            model_name='movimientopago',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='movimientopago',
            name='origenSaldoId',
        ),
        migrations.RemoveField(
            model_name='movimientopago',
            name='tipoMovimientoCajaId',
        ),
        migrations.AddField(
            model_name='movimientopago',
            name='MovimientoCajaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caja.movimientocaja', verbose_name='Movimiento de caja'),
            preserve_default=False,
        ),
    ]
