# Generated by Django 4.2 on 2026-08-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoPago', '0002_movimientopago_movcaj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientopago',
            old_name='MovCaj',
            new_name='MovCaja',
        ),
    ]
