# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=60, verbose_name='Modelos')),
                ('Año', models.DateField(verbose_name='Año')),
                ('MarcaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marcas', verbose_name='Macar')),
            ],
            options={
                'verbose_name_plural': 'Motos',
            },
        ),
    ]
