# Generated by Django 4.2 on 2026-08-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motos',
            name='Año',
        ),
    ]
