# Generated by Django 4.2 on 2026-08-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_remove_motos_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='motos',
            name='Año',
            field=models.IntegerField(default='2026', verbose_name='Año'),
            preserve_default=False,
        ),
    ]
