# Generated by Django 4.2 on 2025-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_cedula_and_more'),
        ('metodoPago', '0001_initial'),
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Factura', models.IntegerField(verbose_name='Número de factura')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('Metodo_PagoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodo_pago', verbose_name='Metodo de pago')),
                ('cajaid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Caja')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Clientes')),
            ],
        ),
    ]
