# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja_empleadoid'),
        ('detalleFactura', '0002_rename_cantidad_detallefactura_cantidad_and_more'),
        ('abono', '0002_abonos_delete_abono'),
        ('clientes', '0003_clientes'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumFactura', models.IntegerField(verbose_name='Número de factura')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('Cajaid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Caja')),
                ('ClienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Clientes')),
            ],
        ),
        migrations.DeleteModel(
            name='factura',
        ),
    ]
