# Generated by Django 4.2 on 2025-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
