# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_productos_delete_producto'),
        ('categoria', '0002_categorias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
