# Generated by Django 4.2 on 2025-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saldo_Inicial', models.IntegerField(verbose_name='Saldo inicial')),
                ('Ingreso', models.IntegerField(verbose_name='Ingreso')),
                ('Egresos', models.IntegerField(verbose_name='Egresos')),
                ('Saldo_Final', models.IntegerField(verbose_name='Saldo final')),
                ('Fecha', models.DateTimeField()),
                ('Num_caja', models.IntegerField(verbose_name='Numero de caja')),
                ('Dinero', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero')),
                ('empleadoid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado', verbose_name='Empleados')),
            ],
        ),
    ]
