# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='Num_caja',
            new_name='NumCaja',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='Ingreso',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='Saldo_Final',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='Saldo_Inicial',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='empleadoid',
        ),
        migrations.AddField(
            model_name='caja',
            name='Ingresos',
            field=models.DecimalField(decimal_places=2, default='sin valor', max_digits=10, verbose_name='Ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='SaldoFinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='SaldoInicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo inicial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='Egresos',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Egresos'),
        ),
    ]
