# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_rename_num_caja_caja_numcaja_remove_caja_ingreso_and_more'),
        ('empleados', '0002_empleados_delete_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='EmpleadoId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='empleados.empleados', verbose_name='Empleados'),
            preserve_default=False,
        ),
    ]
