# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCompra', models.CharField(max_length=100, verbose_name='Número de compra')),
                ('Fecha', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la compra')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='ComprasCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicioCredito', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('montoTotalCredito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total del credito')),
                ('saldoPendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('FechaLimiteCredito', models.DateTimeField(verbose_name='Fecha limite')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ComprasCredito',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio costo')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal')),
                ('estado', models.BooleanField(default=True)),
                ('CompraId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallesCompra', to='compra.compras', verbose_name='Compra')),
            ],
            options={
                'verbose_name_plural': 'Detalles de compra',
            },
        ),
    ]
