# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('metodoPago', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('NumCompra', models.IntegerField(verbose_name='Número de compra')),
                ('Total', models.IntegerField(verbose_name='Total de la compra')),
                ('MetodoPagoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodopago', verbose_name='Metodo de pago')),
                ('ProveedoresId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio costo')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal')),
                ('CompraId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra')),
                ('ProductoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.productos', verbose_name='Productos')),
            ],
        ),
    ]
