# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadoCuenta', '0001_initial'),
        ('condicionPago', '0001_initial'),
        ('compra', '0001_initial'),
        ('proveedor', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='detallProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.detalleproductos', verbose_name='Detalle de Productos'),
        ),
        migrations.AddField(
            model_name='comprascredito',
            name='CompraId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='comprascredito',
            name='estadoCuentaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadoCuenta.estadocuenta', verbose_name='Estado de la factura'),
        ),
        migrations.AddField(
            model_name='compras',
            name='ProveedoresId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedores', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='condicionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condicionPago.condicionpago', verbose_name='Condición del pago'),
        ),
    ]
