# Generated by Django 4.2 on 2025-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_remove_detallecompra_productoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
