# Generated by Django 4.2 on 2026-08-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='condicionId',
            new_name='CondicionPagoId',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='ProveedoresId',
            new_name='ProveedorId',
        ),
        migrations.RenameField(
            model_name='comprascredito',
            old_name='estadoCuentaId',
            new_name='EstadoCuentaId',
        ),
        migrations.RenameField(
            model_name='comprascredito',
            old_name='montoTotalCredito',
            new_name='MontoTotal',
        ),
        migrations.RenameField(
            model_name='comprascredito',
            old_name='saldoPendiente',
            new_name='SaldoPendiente',
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='detallProductoId',
            new_name='DetalleProductoId',
        ),
        migrations.RemoveField(
            model_name='comprascredito',
            name='FechaInicioCredito',
        ),
        migrations.RemoveField(
            model_name='comprascredito',
            name='FechaLimiteCredito',
        ),
        migrations.AddField(
            model_name='comprascredito',
            name='FechaInicio',
            field=models.DateField(default='2026-01-01', verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprascredito',
            name='FechaVencimiento',
            field=models.DateField(default='2026-01-01', verbose_name='Fecha limite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compras',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
