# Generated by Django 4.2 on 2026-04-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condicionPago', '0001_initial'),
        ('estadoCuenta', '0001_initial'),
        ('proveedor', '0002_proveedores_estado'),
        ('compra', '0003_compras_estado_detallecompra_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name_plural': 'Detalles de compra'},
        ),
        migrations.RemoveField(
            model_name='compras',
            name='MetodoPagoId',
        ),
        migrations.AddField(
            model_name='compras',
            name='condicionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='condicionPago.condicionpago', verbose_name='Condición del pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='estadoCuentaId',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='estadoCuenta.estadocuenta', verbose_name='Estado de la factura'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComprasCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicioCredito', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('montoTotalCredito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total del credito')),
                ('saldoPendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('FechaLimiteCredito', models.DateTimeField(verbose_name='Fecha limite')),
                ('estado', models.BooleanField(default=True)),
                ('CompraId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra')),
                ('ProveedoresId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedores', verbose_name='Proveedores')),
            ],
            options={
                'verbose_name_plural': 'ComprasCredito',
            },
        ),
    ]
