# Generated by Django 4.2 on 2026-07-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_detallecompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='CompraId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='compra.compras', verbose_name='Compra'),
        ),
    ]
