# Generated by Django 4.2 on 2026-08-25 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadoCuenta', '0001_initial'),
        ('compra', '0006_alter_detallecompra_compraid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='estadoCuentaId',
        ),
        migrations.AddField(
            model_name='comprascredito',
            name='estadoCuentaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estadoCuenta.estadocuenta', verbose_name='Estado de la factura'),
            preserve_default=False,
        ),
    ]
