# Generated by Django 4.2 on 2026-08-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_remove_compras_estadocuentaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprascredito',
            name='ProveedoresId',
        ),
    ]
