# Generated by Django 4.2 on 2026-07-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dimCliente',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '[dbo].[dimCliente]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dimCondicionPago',
            fields=[
                ('id_CondicionPago', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': '[dbo].[dimCondicionPago]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dimEmpleado',
            fields=[
                ('id_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '[dbo].[dimEmpleado]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dimMetodoPago',
            fields=[
                ('id_MetodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': '[dbo].[dimMetodoPago]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dimProducto',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('Moto', models.CharField(max_length=60, null=True)),
                ('Marca', models.CharField(max_length=50, null=True)),
                ('Categoria', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '[dbo].[dimProducto]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dimTiempo',
            fields=[
                ('id_Tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('Dia', models.IntegerField(null=True)),
                ('Mes', models.IntegerField(null=True)),
                ('Año', models.IntegerField(null=True)),
                ('NombreDia', models.CharField(max_length=10, null=True)),
                ('NombreMes', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': '[dbo].[dimTiempo]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactVenta',
            fields=[
                ('id_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(null=True)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('NumFactura', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '[dbo].[FactVenta]',
                'managed': False,
            },
        ),
    ]
