# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condicionPago', '0001_initial'),
        ('clientes', '0001_initial'),
        ('estadoCuenta', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumFactura', models.IntegerField(verbose_name='Número de factura')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('estado', models.BooleanField(default=True)),
                ('ClienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Clientes')),
                ('condicionId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condicionPago.condicionpago', verbose_name='Condición del pago')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturasCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicioCredito', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('montoTotalCredito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total del credito')),
                ('saldoPendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('FechaLimiteCredito', models.DateTimeField(verbose_name='Fecha limite')),
                ('estado', models.BooleanField(default=True)),
                ('FacturaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='Factura')),
                ('estadoCuentaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadoCuenta.estadocuenta', verbose_name='Estado de la factura')),
            ],
            options={
                'verbose_name_plural': 'FacturasCredito',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio costo')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio costo')),
                ('estado', models.BooleanField(default=True)),
                ('FacturaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='factura.facturas', verbose_name='Factura')),
                ('loteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.registroproducto', verbose_name='Detalle de productos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de factura',
            },
        ),
    ]
