# Generated by Django 4.2 on 2025-11-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='ProductoId',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='detalleProductoId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producto.detalleproductos', verbose_name='Detalle de productos'),
            preserve_default=False,
        ),
    ]
