# Generated by Django 4.2 on 2026-08-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='PrecioUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='Subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
