# Generated by Django 4.2 on 2025-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_remove_detallefactura_productoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
