# Generated by Django 4.2 on 2026-08-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_alter_detallefactura_preciounitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
    ]
