# Generated by Django 4.2 on 2026-08-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_detallefactura_abierta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='abierta',
        ),
    ]
