# Generated by Django 4.2 on 2026-04-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_detallefactura_estado_facturas_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='Cajaid',
        ),
    ]
