# Generated by Django 4.2 on 2026-04-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('clientes', '0002_clientes_estado'),
        ('factura', '0004_remove_facturas_cajaid'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='FacturasCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicioCredito', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('montoTotalCredito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total del credito')),
                ('saldoPendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('FechaLimiteCredito', models.DateTimeField(verbose_name='Fecha limite')),
                ('estado', models.BooleanField(default=True)),
                ('ClienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Clientes')),
                ('FacturaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='Factura')),
            ],
            options={
                'verbose_name_plural': 'FacturasCredito',
            },
        ),
    ]
