# Generated by Django 4.2 on 2026-04-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condicionPago', '0001_initial'),
        ('factura', '0005_facturas_condicionid_facturas_estadocuentaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='condicionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='condicionPago.condicionpago', verbose_name='Condición del pago'),
            preserve_default=False,
        ),
    ]
