# Generated by Django 4.2 on 2026-04-17 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadoCuenta', '0001_initial'),
        ('factura', '0006_facturas_condicionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='estadoCuentaId',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='estadoCuenta.estadocuenta', verbose_name='Estado de la factura'),
            preserve_default=False,
        ),
    ]
