# Generated by Django 4.2 on 2026-04-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_facturas_estadocuentaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='MetodoPagoId',
        ),
    ]
