# Generated by Django 4.2 on 2026-06-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_remove_facturas_metodopagoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='FacturaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='factura.facturas', verbose_name='Factura'),
        ),
    ]
