# Generated by Django 4.2 on 2026-08-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_remove_registro_producto_detalleproductoid_and_more'),
        ('factura', '0009_alter_detallefactura_facturaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='detalleProductoId',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='loteId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producto.registro_producto', verbose_name='Detalle de productos'),
            preserve_default=False,
        ),
    ]
