# Generated by Django 4.2 on 2026-08-25 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadoCuenta', '0001_initial'),
        ('factura', '0010_remove_detallefactura_detalleproductoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='estadoCuentaId',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='PrecioUnitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Precio costo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturascredito',
            name='estadoCuentaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estadoCuenta.estadocuenta', verbose_name='Estado de la factura'),
            preserve_default=False,
        ),
    ]
