# Generated by Django 4.2 on 2026-08-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0011_remove_facturas_estadocuentaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturascredito',
            name='ClienteId',
        ),
    ]
