# Generated by Django 4.2 on 2025-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelos')),
                ('año', models.DateField(verbose_name='Año')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marca', verbose_name='Macar')),
            ],
        ),
    ]
