# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=60, verbose_name='Modelos')),
                ('Año', models.DateField(verbose_name='Año')),
            ],
        ),
        migrations.RemoveField(
            model_name='moto',
            name='marcaId',
        ),
    ]
