# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_productos_delete_producto'),
        ('moto', '0002_motos_remove_moto_marcaid'),
        ('marca', '0003_delete_marca_marcas_tipoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moto',
        ),
        migrations.AddField(
            model_name='motos',
            name='MarcaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marca.marcas', verbose_name='Macar'),
        ),
    ]
