# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('metodoPago', '0001_initial'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAbono', models.DateTimeField(verbose_name='Fecha de abono')),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montos')),
                ('Detalle', models.CharField(max_length=100, verbose_name='Detalle')),
                ('CajaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Caja')),
                ('FacturaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='factura')),
                ('MetodoPagoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodopago', verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name_plural': 'Abonos',
            },
        ),
    ]
