# Generated by Django 4.2 on 2026-08-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abono', '0002_abonos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonos',
            name='CajaId',
        ),
    ]
