# Generated by Django 4.2 on 2026-08-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_turnocaja_remove_movimientocaja_cajaid_delete_caja_and_more'),
        ('abono', '0003_remove_abonos_cajaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonos',
            name='TurnoCajaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caja.turnocaja', verbose_name='Turno de caja'),
            preserve_default=False,
        ),
    ]
