# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
