# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compras_remove_compra_metodo_pagoid_and_more'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
