# Generated by Django 4.2 on 2026-08-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='NumCedula',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='NumTeléfono',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de teléfono'),
        ),
    ]
