# Generated by Django 4.2 on 2025-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cedula',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Num_Telefono',
            field=models.CharField(default='sin número especifico', max_length=8, verbose_name='Número de teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Num_cedula',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
    ]
