# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('NumCedula', models.CharField(max_length=16, null=True, unique=True, verbose_name='Número de cédula')),
                ('NumTeléfono', models.CharField(max_length=8, verbose_name='Número de teléfono')),
            ],
        ),
    ]
