# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_facturas_delete_factura'),
        ('clientes', '0003_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
