# Generated by Django 4.2 on 2025-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo.tipo', verbose_name='Tipo')),
            ],
        ),
    ]
