# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0002_rename_tipo_marca_tipo_tipomarca'),
        ('producto', '0002_productos_delete_producto'),
        ('moto', '0002_motos_remove_moto_marcaid'),
        ('marca', '0002_marcas_remove_marca_tipoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.AddField(
            model_name='marcas',
            name='TipoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo.tipo', verbose_name='Tipo'),
        ),
    ]
