# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='Tipo_Marca',
            new_name='TipoMarca',
        ),
    ]
