# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0002_rename_tipo_marca_tipo_tipomarca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name_plural': 'Tipos'},
        ),
    ]
