CATALOGOS_SETTING_APPS=[
                            'apps.catalogos.clientes',
                            'apps.catalogos.metodoPago',
                            'apps.catalogos.empleados',
                            'apps.catalogos.categoria',
                            'apps.catalogos.proveedor',
                            'apps.catalogos.size',
                            'apps.catalogos.tipo',
                        ] 