# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCaja', models.IntegerField(verbose_name='Numero de caja')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaldoInicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial')),
                ('Egresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Egresos')),
                ('SaldoFinal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo final')),
                ('FechaApertura', models.DateTimeField(verbose_name='Fecha de apertura de la caja')),
                ('FechaCierre', models.DateTimeField(verbose_name='Fecha de cierre de la caja')),
                ('Din_efectivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero en efectivo')),
                ('Din_digital', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero en digital')),
                ('estado', models.BooleanField(default=True)),
                ('EmpleadoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleados', verbose_name='Empleados')),
                ('NumCajaid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Numero de caja')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
