# Generated by Django 4.2 on 2025-11-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaldoInicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial')),
                ('Ingresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingreso')),
                ('Egresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Egresos')),
                ('SaldoFinal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo final')),
                ('Fecha', models.DateTimeField()),
                ('NumCaja', models.IntegerField(verbose_name='Numero de caja')),
                ('Dinero', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero')),
                ('EmpleadoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleados', verbose_name='Empleados')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
