# Generated by Django 4.2 on 2026-08-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('caja', '0001_initial'),
        ('tipoMovimientoCaja', '0001_initial'),
        ('compra', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='compraCreditoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.comprascredito', verbose_name='Compra al credito'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='compraid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='facturaCreditoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.facturascredito', verbose_name='Factura al credito'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='facturaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipoMovimientoCajaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoMovimientoCaja.tipomovimientocaja', verbose_name='Tipo de movimiento'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='turnoCajaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.turnocaja', verbose_name='Turno de caja'),
        ),
    ]
