# Generated by Django 4.2 on 2025-11-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='caja',
            name='FechaApertura',
            field=models.DateTimeField(default='2025-11-24 23:19:36.8120000 +00:00', verbose_name='Fecha de apertura de la caja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='FechaCierre',
            field=models.DateTimeField(default='2025-11-24 23:19:36.8120000 +00:00', verbose_name='Fecha de cierre de la caja'),
            preserve_default=False,
        ),
    ]
