# Generated by Django 4.2 on 2026-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='abierto',
            field=models.BooleanField(default=True, verbose_name='¿Turno Abierto?'),
        ),
        migrations.AlterField(
            model_name='turnocaja',
            name='Din_digital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero en digital'),
        ),
        migrations.AlterField(
            model_name='turnocaja',
            name='Din_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero en efectivo'),
        ),
        migrations.AlterField(
            model_name='turnocaja',
            name='Egresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Egresos'),
        ),
        migrations.AlterField(
            model_name='turnocaja',
            name='FechaCierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre de la caja'),
        ),
        migrations.AlterField(
            model_name='turnocaja',
            name='SaldoFinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final'),
        ),
    ]
