# Generated by Django 4.2 on 2025-11-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_remove_caja_fecha_caja_fechaapertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='FechaApertura',
        ),
    ]
