# Generated by Django 4.2 on 2025-11-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_remove_caja_fechaapertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='FechaApertura',
            field=models.DateTimeField(default='2025-11-24 23:19:36.8120000 +00:00', verbose_name='Fecha de apertura de la caja'),
            preserve_default=False,
        ),
    ]
