# Generated by Django 4.2 on 2026-04-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_remove_facturas_cajaid'),
        ('tipoMovimientoCaja', '0001_initial'),
        ('compra', '0003_compras_estado_detallecompra_estado'),
        ('caja', '0005_caja_fechaapertura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='Dinero',
            new_name='Din_digital',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='Ingresos',
        ),
        migrations.AddField(
            model_name='caja',
            name='Din_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dinero'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('cajaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Caja')),
                ('compraid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.compras', verbose_name='Compra')),
                ('facturaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='Factura')),
                ('tipoMovimientoCajaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoMovimientoCaja.tipomovimientocaja', verbose_name='Tipo de movimiento')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
