# Generated by Django 4.2 on 2026-04-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_rename_dinero_caja_din_digital_remove_caja_ingresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='Din_digital',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero en digital'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Din_efectivo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero en efectivo'),
        ),
    ]
