# Generated by Django 4.2 on 2026-05-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_alter_caja_din_digital_alter_caja_din_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=False),
        ),
    ]
