# Generated by Django 4.2 on 2026-06-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_caja_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
