# Generated by Django 4.2 on 2026-06-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_movimientocaja_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='abierta',
        ),
    ]
