# Generated by Django 4.2 on 2026-08-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleados_estado'),
        ('caja', '0010_remove_caja_abierta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaldoInicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial')),
                ('Egresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Egresos')),
                ('SaldoFinal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo final')),
                ('FechaApertura', models.DateTimeField(verbose_name='Fecha de apertura de la caja')),
                ('FechaCierre', models.DateTimeField(verbose_name='Fecha de cierre de la caja')),
                ('Din_efectivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero en efectivo')),
                ('Din_digital', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero en digital')),
                ('estado', models.BooleanField(default=True)),
                ('EmpleadoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleados', verbose_name='Empleados')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='cajaId',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='turnoCajaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caja.turnocaja', verbose_name='Turno de caja'),
            preserve_default=False,
        ),
    ]
