# Generated by Django 4.2 on 2026-08-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_turnocaja_remove_movimientocaja_cajaid_delete_caja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCaja', models.IntegerField(verbose_name='Numero de caja')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='NumCajaid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Numero de caja'),
            preserve_default=False,
        ),
    ]
