# Generated by Django 4.2 on 2026-08-25 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_remove_facturascredito_clienteid'),
        ('compra', '0008_remove_comprascredito_proveedoresid'),
        ('caja', '0012_caja_turnocaja_numcajaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='compraCreditoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra.comprascredito', verbose_name='Compra al credito'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='facturaCreditoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.facturascredito', verbose_name='Factura al credito'),
        ),
    ]
