# Generated by Django 4.2 on 2025-10-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montos')),
                ('cajaid', models.IntegerField(verbose_name='Caja')),
                ('Fecha_Abono', models.DateField(verbose_name='Fecha de abono')),
                ('facturaid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.factura', verbose_name='factura')),
            ],
        ),
    ]
