# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_facturas_delete_factura'),
        ('metodoPago', '0002_metodopago_delete_metodo_pago'),
        ('abono', '0002_abonos_delete_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonos',
            name='FacturaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.facturas', verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='abonos',
            name='MetodoPagoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodoPago.metodopago', verbose_name='Metodo de pago'),
        ),
    ]
