# Generated by Django 4.2 on 2025-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodoPago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
