# Generated by Django 4.2 on 2025-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_facturas_delete_factura'),
        ('compra', '0003_delete_compra'),
        ('metodoPago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50, verbose_name='Metodo de pago')),
            ],
        ),
        migrations.DeleteModel(
            name='Metodo_Pago',
        ),
    ]
