# Generated by Django 4.2 on 2026-06-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoMovimientoCaja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovimientocaja',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
