# Generated by Django 4.2 on 2026-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origenSaldo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='origensaldo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
